version: '3.9'

services:
  ros2_gazebo:
    build: .
    container_name: ros2_gazebo
    network_mode: host             # allows ROS 2 discovery without bridge
    environment:
      - DISPLAY=${DISPLAY}         # X11 for GUI
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=${XAUTHORITY}
      - TURTLEBOT3_MODEL=burger
      - ROS_DOMAIN_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # share X11 socket
      - ${XAUTHORITY}:${XAUTHORITY}
      - ./ros2_ws:/root/ros2_ws            # workspace mounted
      - ../probabilistic-robotics-playground/src:/root/ros2_ws/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    devices:
      - /dev/dri:/dev/dri
    privileged: true                       # required for GUI + Gazebo physics
    stdin_open: true
    tty: true

