controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters: {}

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    publish_rate: 50
    wheel_separation: 0.16
    wheel_radius: 0.033
    cmd_vel_timeout: 0.25
    base_frame_id: "base_link"
    enable_odom_tf: true
    open_loop: false
